### ISSUE TITLE
Sign In

### ISSUE THREAD

**Issue by xachigami** [sorare/api#15]
Hi,

Can someone please provide a code snippet to sign In, I am having trouble do it. Here is what I do (using python requests)

```
import requests
import bcrypt

user = 'my@mail.com'
password = 'mypassword'
password = password.encode('utf-8')

response = requests.get("https://api.sorare.com/api/v1/users/{0}".format(user))

salt = response.json()['salt'].encode('utf-8')
hashed = bcrypt.hashpw(password, salt).decode('utf-8')

q = """
mutation {
  signIn(input: {email:\""""+user+"""\", password:\""""+hashed+"""\"}) {
    currentUser {
      slug    
    }
    errors {
      message
    }
  }
}
"""
request = requests.post('https://api.sorare.com/graphql', json={'query': q})
```

I get an error
{'data': {'signIn': None},
 'errors': [{'message': 'Cannot return null for non-nullable field UserError.message'}]}

**Comment by Vinedine** [comment]
There is a an example in #12.  Please close this issue if that solves your problem.

**Comment by jeremoquai** [comment]
Hello.

Sorry, quite new to Python and GraphQL...   :-/

Your code doesn't work for me as it returns :

```
Traceback (most recent call last):
  File "C:\Users\Jeremie\Dropbox\perso\projects\python\sorare\test.py", line 9, in <module>
    response = json.loads(r.content)
  File "C:\Users\Jeremie\AppData\Local\Programs\Python\Python38-32\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Jeremie\AppData\Local\Programs\Python\Python38-32\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Jeremie\AppData\Local\Programs\Python\Python38-32\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Any idea ? Many thanks in advance !

**Comment by MarcoSapienza** [comment]
Hello, 
anyone have already resolved this problem?

**Comment by redox** [comment]
Hey @xachigami , I've revamped our documentation and it should now be simpler than ever to sign in programmatically. Let me know what you think about our new README: https://github.com/sorare/api

And thank you @Vinedine !!
