### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by juldu33130** [sorare/api#479]
Has anyone had this error before and if so how do you fix it?
sub.callbacks.received(data.message);
              ^

TypeError: Cannot read properties of undefined (reading 'callbacks')
    at ActionCable.handleMessage (c:\Users\juldu\node_modules\@sorare\actioncable\index.js:159:15)
    at WebSocket.<anonymous> (c:\Users\juldu\node_modules\@sorare\actioncable\index.js:99:17)
    at WebSocket.emit (node:events:514:28)
    at Receiver.receiverOnMessage (c:\Users\juldu\node_modules\ws\lib\websocket.js:1184:20)
    at Receiver.emit (node:events:514:28)
    at Receiver.dataMessage (c:\Users\juldu\node_modules\ws\lib\receiver.js:541:14)
    at Receiver.getData (c:\Users\juldu\node_modules\ws\lib\receiver.js:459:17)
    at Receiver.startLoop (c:\Users\juldu\node_modules\ws\lib\receiver.js:158:22)
    at Receiver._write (c:\Users\juldu\node_modules\ws\lib\receiver.js:84:10)
    at writeOrBuffer (node:internal/streams/writable:392:12)

Node.js v18.17.0

**Comment by juldu33130** [comment]
up!!
