### ISSUE TITLE
Cannot create single sale offer

### ISSUE THREAD

**Issue by zgithubber** [sorare/api#504]
Using https://github.com/sorare/api/blob/master/examples/authorizations.js for listing a card doesn't seem to work, it returns the following error:
TypeError: Cannot convert undefined to a BigInt
    at BigInt (<anonymous>)
    at getTransferMsgHash (/mnt/c/data/Projects/my-sorare-node-js/node_modules/@sorare/crypto/dist/starkware/signature.js:299:18)
    at hashTransfer (/mnt/c/data/Projects/my-sorare-node-js/node_modules/@sorare/crypto/dist/index.js:89:40)
    at signTransfer (/mnt/c/data/Projects/my-sorare-node-js/node_modules/@sorare/crypto/dist/index.js:153:17)
    at signAuthorizationRequest (/mnt/c/data/Projects/my-sorare-node-js/node_modules/@sorare/crypto/dist/index.js:214:12)
    at buildApproval (/mnt/c/data/Projects/my-sorare-node-js/authorizations.js:52:23)
    at /mnt/c/data/Projects/my-sorare-node-js/authorizations.js:95:9
    at Array.map (<anonymous>)

**Comment by Subbitoooo** [comment]
You should try with this Algorithm:
1)Check for undefined:
Before attempting to convert to a BigInt, check if the value is defined. You can use an if statement or the nullish coalescing operator (??) to provide a default value if the variable is undefined.

javascript
Copy code
let myValue = // ... some value that might be undefined

if (myValue !== undefined) {
    let myBigInt = BigInt(myValue);
    // Use myBigInt as needed
}
or using nullish coalescing:

javascript
Copy code
let myBigInt = BigInt(myValue ?? 0);
2)Debugging:
If you're unsure where the undefined value is coming from, you might want to log or debug the variable before the conversion. This can help you identify the root cause of the issue.

3)Handle undefined values gracefully:
If it's acceptable for the value to be undefined, you can add conditional checks to handle it in a way that makes sense for your program.
Hope that you will solve with this algorithm. Just enjoy that!
