### ISSUE TITLE
Cannot mix BigInt and other types in signAuthorizationRequest

### ISSUE THREAD

**Issue by karimess19** [sorare/api#586]
Hello, 

I am trying to implement a Direct offer through the API 

Unable to get the approvals and I have the Error "TypeError: Cannot mix BigInt and other types, use explicit conversions" when calling authorizations.js > buildapproval >  signAuthorizationRequest(privateKey, authorizationRequest);

Not knowing which of my amount should be adjusted (the only input is sendAmount ? could the error be triggered by another reason ? 

here is my prepareOfferInput

{
  type: 'DIRECT_OFFER',
  receiveAssetIds: [
    'xxxxCardAssetIdxxx'
  ],
  sendAssetIds: [],
  sendAmount: { amount: '800000000000000', currency: 'WEI' },
  receiverSlug: 'xxx',
  clientMutationId: '5711213891105153229113',
  settlementCurrencies: [ 'WEI' ]
}

and my AuthorizatinRequest : 
[
  {
    fingerprint: 'xxxx',
    request: {
      __typename: 'StarkexLimitOrderAuthorizationRequest',
      vaultIdSell: 1091253,
      vaultIdBuy: 21536927,
      amountSell: '80000',
      amountBuy: '1',
      tokenSell: 'xxxx',
      tokenBuy: 'xxx',
      nonce: 119,
      expirationTimestamp: 477100,
      feeInfo: null
    }
  }
]

the error details : 
    at hashMsg (/Perso/Projects/nodejs/node_modules/@sorare/crypto/dist/starkware/signature.js:104:34)
    at getLimitOrderMsgHash (/Perso/Projects/nodejs/node_modules/@sorare/crypto/dist/starkware/signature.js:228:10)
    at hashLimitOrder (/Perso/Projects/nodejs/node_modules/@sorare/crypto/dist/index.js:105:42)
    at signLimitOrder (//Perso/Projects/nodejs/node_modules/@sorare/crypto/dist/index.js:168:17)
    at signAuthorizationRequest (/Perso/Projects/nodejs/node_modules/@sorare/crypto/dist/index.js:228:12)

**Comment by karimess19** [comment]
converting amounts by BigInt() resolved the issue.

**Comment by karimess19** [comment]
closed.
